-- luacheck: globals hs

-- Generated by ChatGPT

-- Move the mouse to the center of the currently focused window
hs.hotkey.bind({ "cmd", "ctrl", "alt" }, "D", function()
	-- Get the currently focused window
	local win = hs.window.focusedWindow()

	-- If there is a focused window then proceed
	if win then
		-- Get the frame details of the window
		local f = win:frame()

		-- Calculate the center point of the window
		local center = { x = f.x + f.w / 2, y = f.y + f.h / 2 }

		-- Move the mouse to the center of the window
		hs.mouse.absolutePosition(center)
	end
end)

-- Move the mouse cursor between monitors.
-- Keep track of the current screen index
local currentScreenIndex = 1
hs.hotkey.bind({ "cmd", "alt", "ctrl" }, "N", function()
	-- Get all screens
	local screens = hs.screen.allScreens()

	-- Get the current screen
	local currentScreen = screens[currentScreenIndex]

	-- Get the center of the current screen
	local center = currentScreen:fullFrame().center

	-- Move the mouse to the center of the current screen
	hs.mouse.absolutePosition(center)

	-- Increment the screen index
	currentScreenIndex = currentScreenIndex + 1

	-- If we've gone past the end of the list, wrap around to the beginning
	if currentScreenIndex > #screens then
		currentScreenIndex = 1
	end
end)

-- Move the mouse to the center of the focused window, switch to the next space, and return the mouse to its initial position
hs.hotkey.bind({}, "F17", function()
	local win = hs.window.focusedWindow()
	if win then
		local initialPos = hs.mouse.absolutePosition()
		local screen = win:screen()
		if not hs.geometry.isPointInRect(initialPos, screen:fullFrame()) then
			hs.mouse.absolutePosition(screen:frame().center)
		end
		hs.timer.doAfter(0.02, function()
			hs.mouse.absolutePosition(initialPos)
		end)
	end
end)

local escapePressed = false
local keyPressedWhileHeld = false

local navigationMappings = {
	h = "left",
	j = "down",
	k = "up",
	l = "right",
	d = "pagedown",
	u = "pageup",
	delete = "forwarddelete",
}

local mainEventTap = hs.eventtap.new({ hs.eventtap.event.types.keyDown, hs.eventtap.event.types.keyUp }, function(event)
	local keyCode = event:getKeyCode()
	local char = hs.keycodes.map[keyCode]
	local isDown = event:getType() == hs.eventtap.event.types.keyDown
	local flags = event:getFlags()

	-- Escape key (53)
	if keyCode == 53 then
		if isDown then
			escapePressed = true
			keyPressedWhileHeld = false
		else
			escapePressed = false
			if not keyPressedWhileHeld then
				hs.eventtap.keyStroke({}, "escape", 0)
			end
			keyPressedWhileHeld = false
		end
		return true
	end

	-- § to ` remapping (only on keyDown, consume keyUp too)
	if char == "non_us_backslash" or keyCode == 10 then
		if isDown then
			local mods = {}
			if flags.shift then
				table.insert(mods, "shift")
			end
			if flags.cmd then
				table.insert(mods, "cmd")
			end
			if flags.alt then
				table.insert(mods, "alt")
			end
			if flags.ctrl then
				table.insert(mods, "ctrl")
			end

			hs.eventtap.keyStroke(mods, "`", 0)
		end
		return true
	end

	-- Navigation with modifiers
	if escapePressed and navigationMappings[char] and isDown then
		keyPressedWhileHeld = true

		local mods = {}
		if flags.shift then
			table.insert(mods, "shift")
		end
		if flags.cmd then
			table.insert(mods, "cmd")
		end
		if flags.alt then
			table.insert(mods, "alt")
		end
		if flags.ctrl then
			table.insert(mods, "ctrl")
		end

		hs.eventtap.keyStroke(mods, navigationMappings[char], 0)
		return true
	end

	if escapePressed and navigationMappings[char] and not isDown then
		return true
	end

	return false
end)

mainEventTap:start()
